In [67]:
def get_mirror_cell_pos(r, c, kernel_size, img_h, img_w):
    cell_to_right = c+kernel_size-1
    cell_to_left = c-kernel_size+1
    cell_to_top = r-kernel_size+1
    cell_to_bottom = r+kernel_size-1
    if cell_to_right < img_w and r < img_h and r >= 0:
        return r, cell_to_right
    if cell_to_left >= 0 and r < img_h and r >=0:
        return r, cell_to_left
    if cell_to_top >= 0 and c < img_w and c >= 0:
        return cell_to_top, c
    if cell_to_bottom < img_h and c < img_w and c >= 0:
        return cell_to_bottom, c
    if cell_to_right < img_w and cell_to_top >= 0:
        return cell_to_top, cell_to_right
    if cell_to_right < img_w and cell_to_bottom < img_h:
        return cell_to_bottom, cell_to_right
    if cell_to_left >= 0 and cell_to_top >= 0:
        return cell_to_top, cell_to_left
    if cell_to_left >= 0 and cell_to_bottom < img_h:
        return cell_to_bottom, cell_to_left

In [68]:
def custom_blur(img, kernel_size, border_type='Default'):
    # creating output imgage of same size as input image
    h, w = img.shape[:2]
    output_img = np.zeros((h, w), np.uint8)
    for i in range(len(img)):
        for j in range(len(img[0])):
            # top-left cell's position of kernel after placing it's center over a pixel
            r = i-kernel_size//2
            c = j-kernel_size//2
            # iterating over the kernel and taking average of pixels
            total = 0
            for m in range(r, r+kernel_size):
                for n in range(c, c+kernel_size):
                    # checking if the cell of the kernel is out of bound or not
                    if m < 0 or m > len(img)-1 or n < 0 or n > len(img[0])-1:
                        # out of bound
                        m, n = get_mirror_cell_pos(m, n, kernel_size, h, w)
                        total += img[m][n]
                    else:
                        total += img[m][n]
                avg = round(total/(kernel_size**2))
                # placing avg on the pixel under center of ther kernel
                output_img[i][j] = avg
    return output_img

In [69]:
img = np.empty((0, 5), np.uint8)
for i in range(5):
    img = np.append(img, np.random.randint(0, 255, (1, 5)), axis=0)
img

array([[ 81, 102,  48,  58, 110],
       [232,  35, 198, 103, 236],
       [161,   1, 227,  28,  16],
       [126,  53,  43, 156,  26],
       [188, 120,  45, 124, 173]])

In [72]:
my_custom_blur = custom_blur(img, 3)
blur = cv2.blur(img, (3, 3))

In [75]:
blur, my_custom_blur

(array([[ 99, 129,  98, 143, 123],
        [ 83, 121,  89, 114,  82],
        [ 77, 120,  94, 115,  95],
        [ 91, 107,  89,  93,  92],
        [ 99,  89,  88,  88, 122]], dtype=int32),
 array([[ 99, 129,  98, 143, 123],
        [ 83, 121,  89, 114,  82],
        [ 77, 120,  94, 115,  95],
        [ 91, 107,  89,  93,  92],
        [ 99,  89,  88,  88, 122]], dtype=uint8))